### ISSUE TITLE
Error 0x0000025C16CBC160 | Windows 10

### ISSUE THREAD

**Issue by WOLFA22** [GlUTEN-BASH/discord_crasher#7]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000025C16CBC160>
Traceback (most recent call last):
  File "C:\Users\Local Access User\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Local Access User\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Local Access User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\Local Access User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Оба релиза, что исходник, что исполняемый.

**Comment by GlUTEN-BASH** [comment]
Привет!
Попробуй перегенерировать токен в discord developers
И да, ты мог просто написать в тг вместо того чтобы открывать ошибку

**Comment by GitUser3z** [comment]
Doesnt working
